
import { Product, OfferItem } from './types';

export const PRODUCTS: Product[] = [
  {id:"sugar",category:"مواد غذائية",name:"سكر",price:0.75},
  {id:"rice1",category:"مواد غذائية",name:"رز مصري",price:1.00},
  {id:"rice2",category:"مواد غذائية",name:"رز تايلندي حبة طويلة",price:1.00},
  {id:"oil4",category:"مواد غذائية",name:"زيت 4 لتر",price:8.35},
  {id:"tea",category:"مشروبات",name:"شاي سيدي هشام 25ظ",price:0.95},
  {id:"cashew",category:"مواد غذائية",name:"كاجو",price:10.45},
  {id:"flour", category:"مواد غذائية", name:"طحين 1 كغ", price:1.20},
  {id:"lentils", category:"مواد غذائية", name:"عدس 500 غ", price:0.80},
  {id:"chickpeas", category:"مواد غذائية", name:"حمص 500 غ", price:0.90},
  {id:"coffee_turkish", category:"مشروبات", name:"قهوة تركية 250 غ", price:3.50},
  {id:"juice_orange", category:"مشروبات", name:"عصير برتقال 1 لتر", price:1.10},
  {id:"milk_full", category:"ألبان", name:"حليب كامل الدسم 1 لتر", price:0.90},
  {id:"yogurt_plain", category:"ألبان", name:"لبن عادي 500 غ", price:0.70},
  {id:"cheese_feta", category:"ألبان", name:"جبنة فيتا 200 غ", price:2.20},
  {id:"chicken_breast", category:"لحوم", name:"صدر دجاج 1 كغ", price:6.00},
  {id:"beef_mince", category:"لحوم", name:"لحم عجل مفروم 500 غ", price:7.50},
  {id:"fish_fillet", category:"لحوم", name:"فيليه سمك 300 غ", price:4.50},
  {id:"eggs_dozen", category:"مواد غذائية", name:"بيض (12 بيضة)", price:2.50},
  {id:"bread_arabic", category:"خبز ومعجنات", name:"خبز عربي (5 أرغفة)", price:1.00},
  {id:"pastries_assorted", category:"خبز ومعجنات", name:"معجنات مشكلة 500 غ", price:3.00},
  {id:"detergent_liquid", category:"منظفات", name:"سائل غسيل 1 لتر", price:2.80},
  {id:"soap_bar", category:"منظفات", name:"صابون قالب", price:0.50},
  {id:"shampoo", category:"عناية شخصية", name:"شامبو 400 مل", price:3.00},
  {id:"toothbrush", category:"عناية شخصية", name:"فرشاة أسنان", price:1.20},
  {id:"pasta_spaghetti", category:"مواد غذائية", name:"معكرونة سباغيتي 500 غ", price:0.60},
  {id:"tomato_sauce", category:"مواد غذائية", name:"صلصة طماطم 400 غ", price:0.85},
  {id:"canned_tuna", category:"مواد غذائية", name:"تونا معلبة 185 غ", price:1.50},
  {id:"olives_green", category:"مواد غذائية", name:"زيتون أخضر 300 غ", price:1.75},
  {id:"pickles_mixed", category:"مواد غذائية", name:"مخلل مشكل 500 غ", price:1.30},
  {id:"spices_cumin", category:"بهارات", name:"كمون مطحون 50 غ", price:0.70},
  {id:"spices_paprika", category:"بهارات", name:"بابريكا 50 غ", price:0.65},
  {id:"dates_1kg", category:"فواكه مجففة", name:"تمر 1 كغ", price:3.00},
  {id:"apricots_dried", category:"فواكه مجففة", name:"مشمش مجفف 250 غ", price:2.50},
  {id:"nuts_almonds", category:"مكسرات", name:"لوز 200 غ", price:3.80},
  {id:"chips_potato", category:"وجبات خفيفة", name:"رقائق بطاطس 150 غ", price:1.00},
  {id:"chocolate_bar", category:"حلويات", name:"لوح شوكولاتة", price:0.90},
];

export const SPECIAL_OFFER_ITEMS: OfferItem[] = [
  {id: "sugar5kg", name:"٥ كغ سكر",price:3.75, category: "مواد غذائية"},
  {id: "rice5kg_egyptian", name:"٥ كغ رز مصري",price:5, category: "مواد غذائية"},
  {id: "rice5kg_thai", name:"٥ كغ رز تايلندي",price:5, category: "مواد غذائية"},
  {id: "tomato_paste2kg", name:"٢ كغ دبس بندورة",price:3, category: "مواد غذائية"},
  {id: "klarana_ghee2kg", name:"٢ كغ سمنة كلارنا",price:5.85, category: "مواد غذائية"},
  {id: "sunflower_oil4l", name:"٤ لتر زيت دوار الشمس",price:8.35, category: "مواد غذائية"},
  {id: "coarse_bulgur2kg", name:"٢ كغ برغل خشن",price:1.7, category: "مواد غذائية"},
  {id: "sidi_hisham_tea450g", name:"٤٥٠ غ شاي سيدي هشام",price:5.5, category: "مشروبات"},
  {id: "alhamawi_coffee500g", name:"٥٠٠ غ بن الحموي هال اكسترا",price:8.5, category: "مشروبات"},
  {id: "maggi5cubes", name:"٥ قوالب ماجي",price:1, category: "مواد غذائية"},
  {id: "chicken_thighs2kg", name:"٢ كغ فخاد فروج",price:5, category: "لحوم"},
  {id: "veal_lean1kg", name:"١ كغ لحمة عجل هبرة",price:12, category: "لحوم"},
];
